vim.o.relativenumber = true
vim.o.expandtab = true
vim.opt.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.g.mapleader = " "
--vim.g.terminal = '"C:/Program Files/Git/usr/bin/bash.exe"'
vim.o.listchars = "space:.,tab:|-"
vim.o.foldlevelstart = 99
